import { buildBank, choice } from './helpers';
const cases=[
 ['copper','Cu','pure metal','closely packed identical cores','high electrical conductivity'],['brass','Cu/Zn','substitutional alloy','similar-sized Zn atoms replace Cu atoms','greater hardness than pure copper'],['bronze','Cu/Sn','substitutional alloy','Sn atoms replace some Cu sites','resistance to layer sliding'],['carbon steel','Fe/C','interstitial alloy','small C atoms occupy holes among Fe atoms','greater hardness than pure iron'],['stainless steel','Fe/Cr','substitutional alloy','Cr replaces some Fe lattice sites','corrosion resistance'],
 ['cast iron','Fe/C','interstitial alloy','relatively high C content disrupts Fe layers','hardness with reduced ductility'],['sterling silver','Ag/Cu','substitutional alloy','Cu replaces some Ag sites','greater durability than pure silver'],['gold alloy','Au/Cu','substitutional alloy','similar-sized Cu substitutes for Au','greater hardness than pure gold'],['titanium metal','Ti','pure metal','identical Ti cores share delocalized electrons','metallic conduction'],['tungsten carbide model','metal/small-atom solid','interstitial model','small atoms occupy interstices and hinder motion','very high hardness']
] as const;
const seeds=cases.flatMap(([sample,components,kind,diagram,property])=>[
 {prompt:`Classify ${sample} (${components}) using the listed particle model.`,...choice(kind,[kind,'ionic molecular solid','polar molecular liquid','network of formula-unit molecules']),solution:`${sample} is represented as a ${kind}.`},
 {prompt:`Which particle diagram description matches ${sample}?`,...choice(diagram,[diagram,'alternating positive and negative ions','separate neutral molecules far apart','atoms joined only in isolated pairs']),solution:`The reviewed model is: ${diagram}.`,representation:'particle' as const},
 {prompt:`Which property is consistent with the particle structure of ${sample}?`,...choice(property,[property,'conductivity only after forming ions in water','brittleness caused by alternating anion layers','no attraction between particles']),solution:`Its structure accounts for ${property}.`},
 {prompt:`What feature supplies electrical conduction in ${sample}?`,...choice('delocalized valence electrons that move through the solid',['delocalized valence electrons that move through the solid','fixed anions moving between lattice sites','protons transferred through molecules','isolated covalent bond pairs']),solution:'Mobile, delocalized valence electrons carry electric charge.'},
 {prompt:`Why can alloying in ${sample} change hardness or ductility?`,...choice('different atoms disrupt regular layers and hinder their motion',['different atoms disrupt regular layers and hinder their motion','all atoms lose their nuclei','the alloy becomes a collection of gas molecules','electron charge changes sign']),solution:'Size and placement differences impede the sliding of atomic layers.'}
]);
export const bank24=buildBank('2.4','alloys',seeds);
