import { buildBank, choice } from './helpers';
const bondEvidence = { sourceUrl: 'https://openstax.org/books/chemistry-2e/pages/8-1-valence-bond-theory', locator: 'Section 8.1, representative bond energies and lengths table; H₂ potential-energy figure', method: 'Stored length and energy values checked against the published OpenStax reference table; curve interpretation scope checked against AP Chemistry CED Topic 2.2.', reviewer: 'development-agent', reviewedOn: '2026-09-15', status: 'source-checked', limitation: 'Tabulated bond energies are representative/average instructional values; context and tolerance are part of the record.' };
const cases = [
    ['A', 74, 436, 'H–H'], ['B', 199, 243, 'Cl–Cl'], ['C', 228, 190, 'Br–Br'], ['D', 96, 464, 'O–H'], ['E', 154, 345, 'C–C'],
    ['F', 134, 611, 'C=C'], ['G', 120, 837, 'C≡C'], ['H', 110, 946, 'N≡N'], ['I', 92, 569, 'H–F'], ['J', 127, 432, 'H–Cl']
];
const seeds = cases.flatMap(([curve, length, energy, bond]) => [
    { prompt: `Reviewed curve ${curve} for ${bond} has its minimum at ${length} pm. What is the equilibrium bond length?`, answer: { kind: 'number', value: length, unit: 'pm', tolerance: 1 }, solution: `The equilibrium distance is the x-coordinate of the minimum: ${length} pm.`, representation: 'graph', evidence: bondEvidence },
    { prompt: `Curve ${curve} has a ${energy} kJ mol⁻¹ well depth for ${bond}. How much energy is required to separate one mole of these bonds in this model?`, answer: { kind: 'number', value: energy, unit: 'kJ/mol', tolerance: 2 }, solution: `The well depth relative to separated atoms is ${energy} kJ mol⁻¹.`, representation: 'calculation', evidence: bondEvidence },
    { prompt: `At a separation slightly greater than ${length} pm on curve ${curve}, what is the direction of the net force?`, ...choice('attractive—toward the equilibrium distance', ['attractive—toward the equilibrium distance', 'repulsive—away from equilibrium', 'zero at every distance', 'unrelated to the curve']), solution: 'To the right of the minimum, attraction pulls the atoms back toward equilibrium.', representation: 'graph', evidence: bondEvidence },
    { prompt: `At a separation much smaller than ${length} pm on curve ${curve}, why does potential energy rise steeply?`, ...choice('short-range nucleus–nucleus and electron–electron repulsions dominate', ['short-range nucleus–nucleus and electron–electron repulsions dominate', 'the atoms lose all charged particles', 'gravity becomes dominant', 'the bond energy becomes zero']), solution: 'At very short range, repulsive interactions dominate.', representation: 'graph', evidence: bondEvidence },
    { prompt: `For curve ${curve}, what is true exactly at the ${length} pm minimum?`, ...choice('net force is zero because attraction and repulsion balance', ['net force is zero because attraction and repulsion balance', 'all electrostatic interactions vanish', 'the atoms are infinitely separated', 'potential energy is at a maximum']), solution: 'At the energy minimum, the slope and net force are zero while attractions and repulsions still exist.', representation: 'graph', evidence: bondEvidence }
]);
export const bank22 = buildBank('2.2', 'curve', seeds);
