export const lessons = [
    { topic: '2.1', objectives: ['Classify bonding from particle-level evidence', 'Relate electronegativity and electron distribution', 'Use bonding models to explain properties'], vocabulary: ['electronegativity', 'ionic bond', 'covalent bond', 'metallic bond', 'bond polarity'], sections: [
            { id: 'continuum', title: 'A continuum of electron sharing', body: 'Bonding is best treated as a continuum. Similar electronegativities produce nearly even sharing; a larger difference produces more unequal sharing and partial charges. At the extreme, an ionic model—oppositely charged ions in an extended solid—is most useful. No single cutoff is an infallible law.', example: 'In H–Cl, electron density is pulled toward Cl, so H is δ+ and Cl is δ−.' },
            { id: 'models', title: 'Four useful bonding models', body: 'Nonpolar covalent bonds share density nearly evenly. Polar covalent bonds share it unequally. Ionic solids are repeating arrays of cations and anions held by electrostatic attraction. Metals contain positive ion cores interacting with delocalized valence electrons.' },
            { id: 'properties', title: 'From particles to properties', body: 'Mobile charge carriers allow conduction. Metallic electrons are mobile in the solid; ions in an ionic solid are fixed until melted or dissolved. Directional covalent bonds can form molecules or networks, so “covalent” alone does not determine every bulk property.', example: 'Copper conducts and bends because its delocalized electrons persist while layers of atoms shift.' }
        ], misconceptions: ['Electronegativity difference is not a perfect yes/no boundary.', 'A polar bond does not automatically make the whole molecule polar.'], apGuidance: 'State a claim, cite particle-level evidence, then connect that evidence to the observed property.', summary: 'Bond labels are models of electron distribution; structure and charge mobility explain properties.' },
    { topic: '2.2', objectives: ['Interpret a potential-energy curve', 'Identify equilibrium bond length and bond energy', 'Compare bond strength and length'], vocabulary: ['potential energy', 'equilibrium distance', 'bond length', 'bond energy', 'attraction', 'repulsion'], sections: [
            { id: 'curve', title: 'Reading the curve', body: 'Far apart, interacting atoms approach a zero reference. As attractive interactions dominate, potential energy falls. At very short distance, nucleus–nucleus and electron–electron repulsions rise steeply. The minimum is the stable equilibrium separation.' },
            { id: 'energy', title: 'Depth means energy to separate', body: 'The vertical distance from the minimum to the separated-atom reference is the bond dissociation energy in the model. A deeper well represents a stronger bond. The horizontal position of the minimum represents bond length.', example: 'Curve A with a deeper, left-shifted minimum represents a shorter, stronger bond than curve B.' },
            { id: 'forces', title: 'Slope and competing forces', body: 'To the right of equilibrium, net attraction pulls the atoms together; to the left, net repulsion pushes them apart. At the minimum, the net force is zero—not because interactions vanish, but because opposing contributions balance.' }
        ], misconceptions: ['The minimum is not zero attraction.', 'A deeper well, not a taller positive wall, indicates a stronger bond.'], apGuidance: 'Name both axes, identify the minimum, and compare horizontal position separately from vertical depth.', summary: 'Bond length is the curve minimum’s position; bond energy is its depth relative to separated atoms.' },
    { topic: '2.3', objectives: ['Interpret ionic lattice diagrams', 'Derive formula-unit ratios from charge neutrality', 'Explain brittleness, melting, and conductivity'], vocabulary: ['crystal lattice', 'formula unit', 'coordination', 'electrostatic attraction', 'brittle'], sections: [
            { id: 'lattice', title: 'Extended structures, not molecules', body: 'An ionic solid is a three-dimensional repeating lattice of cations and anions. Its formula gives the simplest whole-number ratio that makes the extended solid electrically neutral; it does not identify a discrete molecule.' },
            { id: 'ratio', title: 'Charge balance determines ratio', body: 'Total positive and negative charge must cancel. Mg²⁺ requires two Cl⁻ ions per formula unit, giving MgCl₂. A diagram sample may contain many formula units but preserves this ratio.' },
            { id: 'properties', title: 'Structure explains behavior', body: 'Strong electrostatic attractions give many ionic solids high melting points. In the solid, ions vibrate around fixed sites and do not conduct. Molten or aqueous ions can move and carry charge. When layers shift, like charges can align and repel, producing brittle fracture.', example: 'NaCl(s) does not conduct; NaCl(l) does because Na⁺ and Cl⁻ are mobile.' }
        ], misconceptions: ['Ionic formulas are ratios, not little molecules.', 'Electrons do not flow freely through a typical ionic solid.'], apGuidance: 'Describe the particles, their arrangement or mobility, and the electrostatic cause of the property.', summary: 'Charge-neutral ratios build repeating lattices whose fixed or mobile ions determine their behavior.' },
    { topic: '2.4', objectives: ['Explain metallic bonding', 'Distinguish substitutional and interstitial alloys', 'Connect particle structure to properties'], vocabulary: ['delocalized electrons', 'malleability', 'ductility', 'substitutional alloy', 'interstitial alloy'], sections: [
            { id: 'metallic', title: 'A collective bonding model', body: 'Metal atoms contribute valence electrons to states delocalized through the solid. Positive ion cores are attracted to this mobile electron density. Because the attraction is not confined to one pair of atoms, layers can shift without all bonding being lost.' },
            { id: 'properties', title: 'Why metals conduct and bend', body: 'Delocalized electrons respond to an electric field, explaining conductivity. Nondirectional attraction remains as cores move, supporting malleability and ductility. Heating increases lattice vibrations and usually increases electrical resistance.' },
            { id: 'alloys', title: 'Two alloy structures', body: 'In a substitutional alloy, similarly sized atoms replace host atoms. In an interstitial alloy, much smaller atoms occupy holes between host atoms. Either can hinder layer motion and increase hardness.', example: 'Brass is substitutional Cu/Zn; carbon steel places smaller C atoms in interstices of Fe.' }
        ], misconceptions: ['Metallic bonding is not neutral atoms floating in an electron liquid with no attraction.', 'An alloy is a solid mixture, not necessarily a new stoichiometric compound.'], apGuidance: 'Use the particle diagram as evidence: compare atom sizes, positions, and the ease of layer movement.', summary: 'Delocalized electrons explain metallic conduction; disrupted layers explain many alloy property changes.' },
    { topic: '2.5', objectives: ['Count total valence electrons', 'Construct and evaluate Lewis diagrams', 'Handle ions, multiple bonds, and AP-scope exceptions'], vocabulary: ['lone pair', 'bonding pair', 'formal charge', 'expanded octet', 'incomplete octet', 'radical'], sections: [
            { id: 'steps', title: 'A reliable construction sequence', body: 'Count valence electrons, adding electrons for negative charge and subtracting for positive charge. Choose a plausible skeleton (H is never central), add single bonds, complete terminal octets, then place remaining electrons on the center. If the center lacks an octet, consider multiple bonds.' },
            { id: 'accounting', title: 'Count every electron once', body: 'Each bond line represents two shared electrons. Lone-pair dots are additional electrons; do not add dots for electrons already represented by a line. Brackets and an overall charge are required for polyatomic ions.', example: 'CO₂ uses 16 valence electrons: O=C=O with two lone pairs on each O.' },
            { id: 'exceptions', title: 'Limits and exceptions', body: 'H follows a duet. Be and B may have incomplete octets. Odd-electron species cannot give every atom an octet. Period 3 and heavier centers can appear expanded in common AP examples. A Lewis diagram represents connectivity and electron bookkeeping, not a complete 3D or electron-density picture.' }
        ], misconceptions: ['The least electronegative atom is only a guide; H is terminal.', 'A correct electron total does not excuse wrong connectivity or formal charges.'], apGuidance: 'Show electron counting explicitly, then use formal charge and known connectivity to justify the preferred drawing.', summary: 'Lewis diagrams are reviewed electron-bookkeeping models built from a counted total and checked structure.' },
    { topic: '2.6', objectives: ['Calculate formal charge', 'Compare candidate contributors', 'Explain resonance and delocalization'], vocabulary: ['formal charge', 'resonance contributor', 'delocalization', 'equivalent bonds', 'major contributor'], sections: [
            { id: 'formal', title: 'Formal charge bookkeeping', body: 'Formal charge = valence electrons − nonbonding electrons − number of bond lines. The sum of all formal charges must equal the species’ overall charge.', example: 'In one nitrate contributor, N has +1; two singly bonded O atoms each have −1; double-bonded O has 0, totaling −1.' },
            { id: 'resonance', title: 'One species, several contributors', body: 'When valid drawings keep the same atom connectivity but place π bonds or charges differently, they are resonance contributors. The real electron distribution is delocalized; the molecule does not switch back and forth between drawings.' },
            { id: 'preference', title: 'Comparing contributors', body: 'Prefer complete octets when applicable, smaller formal-charge magnitudes, and negative formal charge on more electronegative atoms. Equivalent contributors have equal importance and often imply equivalent observed bond lengths.' }
        ], misconceptions: ['Resonance does not move atoms or change connectivity.', 'A zero formal charge is bookkeeping, not proof that an atom has no partial charge.'], apGuidance: 'Calculate every formal charge, verify their sum, then connect equivalent contributors to equivalent measured bonds.', summary: 'Formal charge ranks drawings; resonance combines valid contributors into a delocalized description.' },
    { topic: '2.7', objectives: ['Count electron domains', 'Distinguish electron and molecular geometry', 'Connect AP-scope hybridization and angles'], vocabulary: ['electron domain', 'electron geometry', 'molecular geometry', 'bond angle', 'hybridization'], sections: [
            { id: 'domains', title: 'Count regions around the center', body: 'Each single, double, or triple bond counts as one bonding domain. Each lone pair counts as one nonbonding domain. VSEPR places domains to reduce repulsions; lone pairs usually compress neighboring bond angles.' },
            { id: 'geometry', title: 'Two geometry names answer different questions', body: 'Electron-domain geometry describes all domains; molecular geometry names only atom positions. Four domains give tetrahedral electron geometry. With one lone pair the molecular shape is trigonal pyramidal; with two it is bent.' },
            { id: 'hybrid', title: 'Hybridization in AP scope', body: 'For common central atoms, two, three, and four domains correspond to sp, sp², and sp³ labels. The current AP framework focuses hybridization on these cases; expanded-octet d-hybrid labels are not assessed here, so the reference marks them “not assessed.”', example: 'CO₂: 2 domains, linear, 180°, sp. NH₃: 4 domains, tetrahedral electron geometry, trigonal pyramidal molecular geometry, about 107°, sp³.' }
        ], misconceptions: ['A double bond counts as one domain, not two.', 'Bent molecules can come from three or four electron domains.'], apGuidance: 'Start from a verified Lewis diagram; count domains before naming either geometry or an angle.', summary: 'Domain count determines electron geometry; lone pairs change the molecular geometry and often the angle.' }
];
export const vseprRows = [
    [2, 2, 0, 'linear', 'linear', '180°', 'sp', 'CO₂'],
    [3, 3, 0, 'trigonal planar', 'trigonal planar', '120°', 'sp²', 'BF₃'],
    [3, 2, 1, 'trigonal planar', 'bent', '<120°', 'sp²', 'SO₂'],
    [4, 4, 0, 'tetrahedral', 'tetrahedral', '109.5°', 'sp³', 'CH₄'],
    [4, 3, 1, 'tetrahedral', 'trigonal pyramidal', '≈107°', 'sp³', 'NH₃'],
    [4, 2, 2, 'tetrahedral', 'bent', '≈104.5°', 'sp³', 'H₂O'],
    [5, 5, 0, 'trigonal bipyramidal', 'trigonal bipyramidal', '90°, 120°, 180°', 'not assessed', 'PCl₅'],
    [5, 4, 1, 'trigonal bipyramidal', 'seesaw', '<90°, <120°, ≈180°', 'not assessed', 'SF₄'],
    [5, 3, 2, 'trigonal bipyramidal', 'T-shaped', '≈90°, 180°', 'not assessed', 'ClF₃'],
    [5, 2, 3, 'trigonal bipyramidal', 'linear', '180°', 'not assessed', 'XeF₂'],
    [6, 6, 0, 'octahedral', 'octahedral', '90°, 180°', 'not assessed', 'SF₆'],
    [6, 5, 1, 'octahedral', 'square pyramidal', '≈90°, 180°', 'not assessed', 'BrF₅'],
    [6, 4, 2, 'octahedral', 'square planar', '90°, 180°', 'not assessed', 'XeF₄']
];
