import { useRef, useState, type PointerEvent } from 'react';

type ElementInfo={z:number;symbol:string;name:string;mass:string;group:number;period:number;category:string};
const main=[
['H','Hydrogen','1.008',1,1,'nonmetal'],['He','Helium','4.0026',18,1,'noble'],['Li','Lithium','6.94',1,2,'alkali'],['Be','Beryllium','9.0122',2,2,'alkaline'],['B','Boron','10.81',13,2,'metalloid'],['C','Carbon','12.011',14,2,'nonmetal'],['N','Nitrogen','14.007',15,2,'nonmetal'],['O','Oxygen','15.999',16,2,'nonmetal'],['F','Fluorine','18.998',17,2,'halogen'],['Ne','Neon','20.180',18,2,'noble'],
['Na','Sodium','22.990',1,3,'alkali'],['Mg','Magnesium','24.305',2,3,'alkaline'],['Al','Aluminum','26.982',13,3,'post-transition'],['Si','Silicon','28.085',14,3,'metalloid'],['P','Phosphorus','30.974',15,3,'nonmetal'],['S','Sulfur','32.06',16,3,'nonmetal'],['Cl','Chlorine','35.45',17,3,'halogen'],['Ar','Argon','39.948',18,3,'noble'],
['K','Potassium','39.098',1,4,'alkali'],['Ca','Calcium','40.078',2,4,'alkaline'],['Sc','Scandium','44.956',3,4,'transition'],['Ti','Titanium','47.867',4,4,'transition'],['V','Vanadium','50.942',5,4,'transition'],['Cr','Chromium','51.996',6,4,'transition'],['Mn','Manganese','54.938',7,4,'transition'],['Fe','Iron','55.845',8,4,'transition'],['Co','Cobalt','58.933',9,4,'transition'],['Ni','Nickel','58.693',10,4,'transition'],['Cu','Copper','63.546',11,4,'transition'],['Zn','Zinc','65.38',12,4,'transition'],['Ga','Gallium','69.723',13,4,'post-transition'],['Ge','Germanium','72.630',14,4,'metalloid'],['As','Arsenic','74.922',15,4,'metalloid'],['Se','Selenium','78.971',16,4,'nonmetal'],['Br','Bromine','79.904',17,4,'halogen'],['Kr','Krypton','83.798',18,4,'noble'],
['Rb','Rubidium','85.468',1,5,'alkali'],['Sr','Strontium','87.62',2,5,'alkaline'],['Y','Yttrium','88.906',3,5,'transition'],['Zr','Zirconium','91.224',4,5,'transition'],['Nb','Niobium','92.906',5,5,'transition'],['Mo','Molybdenum','95.95',6,5,'transition'],['Tc','Technetium','[98]',7,5,'transition'],['Ru','Ruthenium','101.07',8,5,'transition'],['Rh','Rhodium','102.91',9,5,'transition'],['Pd','Palladium','106.42',10,5,'transition'],['Ag','Silver','107.87',11,5,'transition'],['Cd','Cadmium','112.41',12,5,'transition'],['In','Indium','114.82',13,5,'post-transition'],['Sn','Tin','118.71',14,5,'post-transition'],['Sb','Antimony','121.76',15,5,'metalloid'],['Te','Tellurium','127.60',16,5,'metalloid'],['I','Iodine','126.90',17,5,'halogen'],['Xe','Xenon','131.29',18,5,'noble'],
['Cs','Cesium','132.91',1,6,'alkali'],['Ba','Barium','137.33',2,6,'alkaline'],['La','Lanthanum','138.91',3,6,'lanthanide'],['Hf','Hafnium','178.49',4,6,'transition'],['Ta','Tantalum','180.95',5,6,'transition'],['W','Tungsten','183.84',6,6,'transition'],['Re','Rhenium','186.21',7,6,'transition'],['Os','Osmium','190.23',8,6,'transition'],['Ir','Iridium','192.22',9,6,'transition'],['Pt','Platinum','195.08',10,6,'transition'],['Au','Gold','196.97',11,6,'transition'],['Hg','Mercury','200.59',12,6,'transition'],['Tl','Thallium','204.38',13,6,'post-transition'],['Pb','Lead','207.2',14,6,'post-transition'],['Bi','Bismuth','208.98',15,6,'post-transition'],['Po','Polonium','[209]',16,6,'post-transition'],['At','Astatine','[210]',17,6,'halogen'],['Rn','Radon','[222]',18,6,'noble'],
['Fr','Francium','[223]',1,7,'alkali'],['Ra','Radium','[226]',2,7,'alkaline'],['Ac','Actinium','[227]',3,7,'actinide'],['Rf','Rutherfordium','[267]',4,7,'transition'],['Db','Dubnium','[268]',5,7,'transition'],['Sg','Seaborgium','[269]',6,7,'transition'],['Bh','Bohrium','[270]',7,7,'transition'],['Hs','Hassium','[269]',8,7,'transition'],['Mt','Meitnerium','[278]',9,7,'unknown'],['Ds','Darmstadtium','[281]',10,7,'unknown'],['Rg','Roentgenium','[282]',11,7,'unknown'],['Cn','Copernicium','[285]',12,7,'transition'],['Nh','Nihonium','[286]',13,7,'unknown'],['Fl','Flerovium','[289]',14,7,'post-transition'],['Mc','Moscovium','[290]',15,7,'unknown'],['Lv','Livermorium','[293]',16,7,'unknown'],['Ts','Tennessine','[294]',17,7,'halogen'],['Og','Oganesson','[294]',18,7,'noble']
] as const;
const fblock=[
['Ce','Cerium','140.12','lanthanide'],['Pr','Praseodymium','140.91','lanthanide'],['Nd','Neodymium','144.24','lanthanide'],['Pm','Promethium','[145]','lanthanide'],['Sm','Samarium','150.36','lanthanide'],['Eu','Europium','151.96','lanthanide'],['Gd','Gadolinium','157.25','lanthanide'],['Tb','Terbium','158.93','lanthanide'],['Dy','Dysprosium','162.50','lanthanide'],['Ho','Holmium','164.93','lanthanide'],['Er','Erbium','167.26','lanthanide'],['Tm','Thulium','168.93','lanthanide'],['Yb','Ytterbium','173.05','lanthanide'],['Lu','Lutetium','174.97','lanthanide'],
['Th','Thorium','232.04','actinide'],['Pa','Protactinium','231.04','actinide'],['U','Uranium','238.03','actinide'],['Np','Neptunium','[237]','actinide'],['Pu','Plutonium','[244]','actinide'],['Am','Americium','[243]','actinide'],['Cm','Curium','[247]','actinide'],['Bk','Berkelium','[247]','actinide'],['Cf','Californium','[251]','actinide'],['Es','Einsteinium','[252]','actinide'],['Fm','Fermium','[257]','actinide'],['Md','Mendelevium','[258]','actinide'],['No','Nobelium','[259]','actinide'],['Lr','Lawrencium','[266]','actinide']
] as const;
const atomicNumbers:Record<string,number>={};
['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'].forEach((s,i)=>atomicNumbers[s]=i+1);
const elements:ElementInfo[]=[...main.map(([symbol,name,mass,group,period,category])=>({z:atomicNumbers[symbol],symbol,name,mass,group,period,category})),...fblock.map(([symbol,name,mass,category],i)=>({z:atomicNumbers[symbol],symbol,name,mass,group:4+i%14,period:i<14?8:9,category}))];

type ResizeEdge='n'|'s'|'e'|'w'|'ne'|'nw'|'se'|'sw';
export function PeriodicTableWindow({onClose}:{onClose:()=>void}){
 const initialWidth=Math.min(850,window.innerWidth*.96),initialHeight=Math.min(690,window.innerHeight-110);
 const [selected,setSelected]=useState(elements[0]),[position,setPosition]=useState({x:Math.max(12,window.innerWidth-initialWidth-20),y:92}),[size,setSize]=useState({width:initialWidth,height:initialHeight});
 const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const resizing=useRef<{edge:ResizeEdge;x:number;y:number;left:number;top:number;width:number;height:number}|null>(null);
 const down=(e:PointerEvent<HTMLDivElement>)=>{drag.current={x:e.clientX,y:e.clientY,left:position.x,top:position.y};e.currentTarget.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent<HTMLDivElement>)=>{if(!drag.current)return;setPosition({x:Math.max(0,Math.min(window.innerWidth-320,drag.current.left+e.clientX-drag.current.x)),y:Math.max(0,Math.min(window.innerHeight-80,drag.current.top+e.clientY-drag.current.y))})};
 const up=(e:PointerEvent<HTMLDivElement>)=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
 const resizeDown=(edge:ResizeEdge)=>(e:PointerEvent<HTMLDivElement>)=>{e.stopPropagation();resizing.current={edge,x:e.clientX,y:e.clientY,left:position.x,top:position.y,width:size.width,height:size.height};e.currentTarget.setPointerCapture(e.pointerId)};
 const resizeMove=(e:PointerEvent<HTMLDivElement>)=>{const r=resizing.current;if(!r)return;const dx=e.clientX-r.x,dy=e.clientY-r.y,minW=320,minH=280;let width=r.width+(r.edge.includes('e')?dx:r.edge.includes('w')?-dx:0),height=r.height+(r.edge.includes('s')?dy:r.edge.includes('n')?-dy:0),left=r.left+(r.edge.includes('w')?dx:0),top=r.top+(r.edge.includes('n')?dy:0);if(width<minW){if(r.edge.includes('w'))left-=minW-width;width=minW}if(height<minH){if(r.edge.includes('n'))top-=minH-height;height=minH}width=Math.min(width,window.innerWidth-left);height=Math.min(height,window.innerHeight-top);setPosition({x:Math.max(0,left),y:Math.max(0,top)});setSize({width,height})};
 const resizeUp=(e:PointerEvent<HTMLDivElement>)=>{resizing.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
 return <aside className="periodic-window" style={{left:position.x,top:position.y,width:size.width,height:size.height}} aria-label="Interactive periodic table">
  <div className="periodic-titlebar" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><div><span className="window-dot"/>Interactive periodic table</div><span>Drag to move</span><button aria-label="Close periodic table" onPointerDown={e=>e.stopPropagation()} onClick={onClose}>×</button></div>
  <div className="periodic-content"><div className="element-detail" aria-live="polite"><span className={`element-preview ${selected.category}`}><small>{selected.z}</small><strong>{selected.symbol}</strong></span><div><strong>{selected.name}</strong><span>Atomic number {selected.z}</span><span>Atomic mass {selected.mass} u</span><span>{selected.category.replace('-', ' ')}</span></div></div><p className="periodic-help">Hover, focus, or tap an element for details.</p>
   <div className="periodic-grid">{elements.map(el=><button key={el.z} className={`periodic-element ${el.category}`} style={{gridColumn:el.group,gridRow:el.period}} onMouseEnter={()=>setSelected(el)} onFocus={()=>setSelected(el)} onClick={()=>setSelected(el)} aria-label={`${el.name}, atomic number ${el.z}, atomic mass ${el.mass}`}><small>{el.z}</small><strong>{el.symbol}</strong></button>)}</div>
   <div className="periodic-legend"><span className="transition">Transition metal</span><span className="metalloid">Metalloid</span><span className="nonmetal">Nonmetal</span><span className="halogen">Halogen</span><span className="noble">Noble gas</span></div>
  </div>
  {(['n','s','e','w','ne','nw','se','sw'] as ResizeEdge[]).map(edge=><div key={edge} className={`resize-handle resize-${edge}`} aria-hidden="true" onPointerDown={resizeDown(edge)} onPointerMove={resizeMove} onPointerUp={resizeUp} onPointerCancel={resizeUp}/>)}
 </aside>
}
