import type { TopicId } from '../content/types';

type VisualKind='continuum'|'models'|'mobility'|'curve'|'wells'|'forces'|'lattice'|'charges'|'fracture'|'sea'|'conduct'|'alloys'|'lewis-steps'|'co2'|'exceptions'|'formal'|'resonance'|'ranking'|'domains'|'shapes'|'hybrid';
type Guide={title:string;steps:string[];tip:string;visual:VisualKind};
const guides:Record<string,Guide>={
 '2.1:continuum':{title:'Classify a bond from electron pull',steps:['Find the two elements and compare their electronegativities.','A small difference means nearly even sharing; a moderate difference means unequal sharing.','For a very large difference with a metal and nonmetal, use an ionic model.','State where electron density is concentrated and label δ+ / δ− when appropriate.'],tip:'Difference tells distribution—not a magical hard boundary.',visual:'continuum'},
 '2.1:models':{title:'Choose the useful bonding model',steps:['Identify the particles: atoms, ions, molecules, or metal cores.','Ask whether electrons are localized in bonds, transferred, or delocalized.','Match the evidence to nonpolar covalent, polar covalent, ionic, or metallic.'],tip:'Name the particles before naming the bond.',visual:'models'},
 '2.1:properties':{title:'Explain a bulk property',steps:['Name the charge carrier or structural feature.','Decide whether it can move in the stated phase.','Connect that mobility or rigidity to conductivity, melting, hardness, or bending.'],tip:'Particle + arrangement + motion → property.',visual:'mobility'},
 '2.2:curve':{title:'Read any potential-energy curve',steps:['Read distance on x and potential energy on y.','Locate the lowest point of the curve.','Drop to x for equilibrium bond length; measure up to zero for bond energy.'],tip:'Minimum x = length; well depth = strength.',visual:'curve'},
 '2.2:energy':{title:'Compare two bonds',steps:['Compare the horizontal positions of the minima.','The leftmost minimum is the shorter bond.','Compare depth below zero; the deeper well is the stronger bond.','Make two separate claims—shorter does not mean you can skip the energy evidence.'],tip:'Left = short. Deep = strong.',visual:'wells'},
 '2.2:forces':{title:'Predict the restoring force',steps:['Mark the equilibrium distance.','Left of it, repulsion dominates and pushes atoms apart.','Right of it, attraction dominates and pulls atoms together.','At the minimum, opposing forces balance and net force is zero.'],tip:'The slope points you back toward equilibrium.',visual:'forces'},
 '2.3:lattice':{title:'Interpret an ionic particle diagram',steps:['Identify cations and anions by sign or relative size.','Look for a repeating alternating pattern, not isolated molecules.','Count a representative region and reduce to the simplest ratio.'],tip:'A formula unit is a ratio, not a molecule.',visual:'lattice'},
 '2.3:ratio':{title:'Write an ionic formula',steps:['Write each ion with its charge.','Choose the smallest counts that make total charge zero.','Use those counts as subscripts and reduce if needed.','Check: positive charge + negative charge = 0.'],tip:'Criss-cross only as a shortcut; neutrality is the reason.',visual:'charges'},
 '2.3:properties':{title:'Link lattice structure to behavior',steps:['In a solid, ions are fixed: no electrical conduction.','When molten or dissolved, ions move: conduction becomes possible.','When layers shift, like charges align and repel: the crystal fractures.'],tip:'Fixed ions, mobile ions, shifted ions.',visual:'fracture'},
 '2.4:metallic':{title:'Build the metallic-bonding explanation',steps:['Picture positive metal cores in a repeating array.','Valence electrons are delocalized across the solid.','Electrostatic attraction between cores and mobile electron density holds the solid together.'],tip:'Cores are positive—not neutral atoms in a sea.',visual:'sea'},
 '2.4:properties':{title:'Explain conduction and malleability',steps:['Mobile electrons respond to an electric field and carry charge.','Metallic attraction is nondirectional.','Layers can slide while attraction to the electron density remains.'],tip:'Mobile electrons conduct; nondirectional bonding bends.',visual:'conduct'},
 '2.4:alloys':{title:'Classify and explain an alloy',steps:['Compare the added atom’s radius with the host radius.','Similar size and a lattice-site replacement means substitutional.','Much smaller and in a gap means interstitial.','Explain hardness: size mismatch blocks easy layer sliding.'],tip:'Replace = substitutional. Gap = interstitial.',visual:'alloys'},
 '2.5:steps':{title:'Draw a Lewis structure reliably',steps:['Count all valence electrons and adjust for charge.','Choose a skeleton; hydrogen is always terminal.','Add single bonds and complete terminal octets.','Put leftovers on the center; make multiple bonds if the center still lacks an octet.','Check total electrons and formal charges.'],tip:'Count → connect → outside → center → check.',visual:'lewis-steps'},
 '2.5:accounting':{title:'Audit every electron exactly once',steps:['Each bond line represents 2 electrons.','Each lone-pair dot represents 1 electron.','Add line electrons and dot electrons; match the original total.','For ions, add brackets and the overall charge.'],tip:'Lines already count—never add their electrons again.',visual:'co2'},
 '2.5:exceptions':{title:'Recognize an octet exception',steps:['Hydrogen needs 2 electrons.','Beryllium and boron can be stable with incomplete octets.','An odd total means one unpaired electron must remain.','Period 3 or heavier centers may exceed eight in common AP examples.'],tip:'H duet; Be/B short; odd radical; row 3+ expanded.',visual:'exceptions'},
 '2.6:formal':{title:'Calculate formal charge',steps:['Write the atom’s normal valence count.','Subtract all nonbonding electrons.','Subtract one for each bond line.','Repeat for every atom and verify the charges sum to the overall charge.'],tip:'FC = valence − dots − lines.',visual:'formal'},
 '2.6:resonance':{title:'Create resonance contributors',steps:['Keep the same atoms and sigma-bond skeleton.','Move only π electrons or lone pairs.','Recalculate formal charges after each move.','Connect valid contributors with a double-headed resonance arrow.'],tip:'Electrons move in drawings; atoms do not.',visual:'resonance'},
 '2.6:preference':{title:'Rank contributors',steps:['Reject drawings with impossible electron counts.','Prefer complete octets when applicable.','Prefer smaller formal-charge magnitudes.','Place negative charge on the more electronegative atom.','Treat symmetry-equivalent contributors as equally important.'],tip:'Octets → small charges → negative on electronegative.',visual:'ranking'},
 '2.7:domains':{title:'Count electron domains',steps:['Start from a verified Lewis structure.','Each single, double, or triple bond counts as one domain.','Each lone pair counts as one domain.','Add them around the central atom only.'],tip:'One connected region = one domain.',visual:'domains'},
 '2.7:geometry':{title:'Name both geometries',steps:['Use total domains for electron geometry.','Ignore lone pairs when naming molecular geometry.','Use lone pairs to predict angle compression.','State the ideal or approximate angle appropriate to the shape.'],tip:'Electron geometry counts everything; molecular geometry sees atoms.',visual:'shapes'},
 '2.7:hybrid':{title:'Assign AP-scope hybridization',steps:['Count domains around the central atom.','Two domains → sp; three → sp²; four → sp³.','Use the same count to verify linear, trigonal-planar, or tetrahedral electron geometry.'],tip:'2–3–4 domains maps to sp–sp²–sp³.',visual:'hybrid'}
};

export function StepVisual({topic,section}:{topic:TopicId;section:string}){const guide=guides[`${topic}:${section}`];if(!guide)return null;return <section className="step-visual" aria-label={`Step-by-step guide: ${guide.title}`}><div className="step-guide"><p className="eyebrow">STEP-BY-STEP</p><h3>{guide.title}</h3><ol>{guide.steps.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol><p className="memory-tip"><strong>Memory shortcut:</strong> {guide.tip}</p></div><ConceptVisual kind={guide.visual}/></section>}

function ConceptVisual({kind}:{kind:VisualKind}){switch(kind){
 case'continuum':return <div className="concept-visual continuum"><div><span>Even sharing</span><span>Unequal sharing</span><span>Ion model</span></div><strong>Nonpolar → Polar → Ionic character</strong></div>;
 case'models':return <div className="concept-visual model-quads">{[['H—H','Nonpolar'],['H—Cl','Polar'],['+ − + −','Ionic'],['⊕ e⁻ ⊕','Metallic']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div>;
 case'mobility':return <div className="concept-visual flow"><b>Particles</b><i>→</i><b>Arrangement</b><i>→</i><b>Movement</b><i>→</i><b>Property</b></div>;
 case'curve':case'wells':return <svg className="concept-visual energy-svg" viewBox="0 0 360 190" role="img" aria-label="Potential energy well"><path d="M25 30V165H340"/><path className="curve-a" d="M30 55 C110 58 115 152 172 152 C220 152 210 60 335 55"/><path className={kind==='wells'?'curve-b':'hidden'} d="M30 55 C155 58 170 120 225 120 C270 120 265 60 335 55"/><line x1="172" y1="152" x2="172" y2="165"/><text x="135" y="182">bond length</text><text x="5" y="20">PE</text></svg>;
 case'forces':return <div className="concept-visual force-line"><span>← Repulsion</span><b>equilibrium</b><span>Attraction →</span></div>;
 case'lattice':case'fracture':return <div className={`concept-visual ion-grid ${kind}`}>{Array.from({length:20},(_,i)=><span key={i} className={(i+Math.floor(i/5))%2?'minus':'plus'}>{(i+Math.floor(i/5))%2?'−':'+'}</span>)}</div>;
 case'charges':return <div className="concept-visual charge-balance"><div>Mg<sup>2+</sup></div><strong>+</strong><div>2 Cl<sup>−</sup></div><strong>=</strong><div>0</div></div>;
 case'sea':case'conduct':return <div className="concept-visual electron-sea">{Array.from({length:12},(_,i)=><span key={i}>⊕</span>)}<p>e⁻ &nbsp; e⁻ &nbsp; e⁻ &nbsp; e⁻ {kind==='conduct'&&' →'}</p></div>;
 case'alloys':return <div className="concept-visual alloy-mini"><div><b>● ● ●</b><b>● ◉ ●</b><span>replace</span></div><div><b>● · ●</b><b>● ● ●</b><span>gap</span></div></div>;
 case'lewis-steps':return <div className="concept-visual flow"><b>Count</b><i>→</i><b>Skeleton</b><i>→</i><b>Octets</b><i>→</i><b>Check</b></div>;
 case'co2':return <div className="concept-visual lewis-demo"><span>··</span><strong>O=C=O</strong><span>··</span><small>4 bond lines = 8 e⁻ · dots = 8 e⁻ · total 16</small></div>;
 case'exceptions':return <div className="concept-visual model-quads"><div><b>H</b><span>2</span></div><div><b>B</b><span>6</span></div><div><b>NO</b><span>odd</span></div><div><b>PCl₅</b><span>10</span></div></div>;
 case'formal':return <div className="concept-visual formula-box"><strong>FC = V − N − B</strong><span>valence − nonbonding e⁻ − bond lines</span></div>;
 case'resonance':return <div className="concept-visual resonance-demo"><b>O—N=O</b><strong>↔</strong><b>O=N—O</b><small>same atoms · moved π electrons</small></div>;
 case'ranking':return <div className="concept-visual checklist"><span>✓ octets</span><span>✓ small |FC|</span><span>✓ − on electronegative atom</span></div>;
 case'domains':return <div className="concept-visual domain-demo"><b>O═C═O</b><span>2 connected regions → 2 domains</span></div>;
 case'shapes':return <div className="concept-visual model-quads"><div><b>2</b><span>linear</span></div><div><b>3</b><span>trigonal planar</span></div><div><b>4</b><span>tetrahedral</span></div></div>;
 case'hybrid':return <div className="concept-visual hybrid-ladder"><span>2 → sp → 180°</span><span>3 → sp² → 120°</span><span>4 → sp³ → 109.5°</span></div>;
 }}
