import { useEffect, useState } from 'react';
import { units, topics } from './content/config';
import { LessonView } from './components/LessonView';
import { PracticeView } from './components/PracticeView';
import { APPracticeView } from './components/APPracticeView';
import { PeriodicTableWindow } from './components/PeriodicTableWindow';
import { BlueSheetPage } from './components/BlueSheetPage';
import type { TopicId } from './content/types';

const getPath=()=>location.hash.slice(1)||'/';
export default function App(){const [path,setPath]=useState(getPath),[periodicOpen,setPeriodicOpen]=useState(false);useEffect(()=>{const f=()=>setPath(getPath());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const navigate=(p:string)=>{location.hash=p;setPath(p);if(typeof scrollTo==='function')scrollTo({top:0,behavior:typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 const ap=path.match(/^\/practice\/ap\/(2(?:\.[1-7])?)$/);if(ap)return <APPracticeView scope={ap[1] as TopicId|'2'} navigate={navigate}/>;
 const concepts=path.match(/^\/practice\/concepts\/(2(?:\.[1-7])?)$/),m=path.match(/^\/(learn|practice)\/(2\.[1-7])/);let content;if(concepts)content=<PracticeView topic={concepts[1] as TopicId|'2'} navigate={navigate}/>;else if(m)content=m[1]==='learn'?<LessonView topic={m[2] as TopicId} navigate={navigate}/>:<PracticeView topic={m[2] as TopicId} navigate={navigate}/>;else if(path==='/unit/2')content=<UnitDashboard navigate={navigate}/>;else if(path==='/blue-sheet')content=<BlueSheetPage navigate={navigate}/>;else content=<Dashboard navigate={navigate}/>;
 return <><header className="site-header"><button className="brand" onClick={()=>navigate('/')}><span>AP Chemistry</span><small>By AP</small></button><nav aria-label="Primary"><button onClick={()=>navigate('/')}>Units</button><button onClick={()=>navigate('/unit/2')}>Unit 2</button><button onClick={()=>navigate('/blue-sheet')}>Blue Sheet</button><button className="periodic-trigger" aria-expanded={periodicOpen} onClick={()=>setPeriodicOpen(v=>!v)}><span aria-hidden="true">⚛</span> Periodic table</button></nav></header>{periodicOpen&&<PeriodicTableWindow onClose={()=>setPeriodicOpen(false)}/>} {content}<footer><strong>AP Chemistry</strong><span>Independent learning and practice resource. Not affiliated with or endorsed by the College Board.</span><span>No accounts. No scores. No tracking.</span></footer></>}
function Dashboard({navigate}:{navigate:(p:string)=>void}){return <main id="main" className="page"><header className="hero"><p className="eyebrow">INTERACTIVE LEARNING + PRACTICE</p><h1>Build chemical intuition.<br/><em>One structure at a time.</em></h1><p>Explore particle models, construct Lewis diagrams, and explain how microscopic structure produces observable properties.</p><button className="primary" onClick={()=>navigate('/unit/2')}>Explore active Unit 2 <span>→</span></button><div className="hero-stats"><div><strong>7</strong><span>complete topics</span></div><div><strong>350</strong><span>reviewed problems</span></div><div><strong>∞</strong><span>help, never tracked</span></div></div></header><section><div className="section-head"><div><p className="eyebrow">COURSE MAP</p><h2>Nine AP Chemistry units</h2></div><p>Unit 2 is ready now. The architecture is prepared for the rest without sending you to empty screens.</p></div><div className="unit-grid">{units.map(([n,title])=><article key={n} className={n==='2'?'active unit-card':'unit-card'}><span className="unit-index">0{n}</span><div><p>{n==='2'?'AVAILABLE NOW':'COMING LATER'}</p><h3>{title}</h3>{n==='2'&&<button onClick={()=>navigate('/unit/2')}>Open unit <span>→</span></button>}</div></article>)}</div></section></main>}
function UnitDashboard({navigate}:{navigate:(p:string)=>void}){return <main id="main" className="page"><nav className="crumbs"><button onClick={()=>navigate('/')}>All units</button><span>/</span><span>Unit 2</span></nav><header className="unit-hero"><p className="eyebrow">UNIT 2 · 7–9% OF AP EXAM</p><h1>Compound Structure<br/>and Properties</h1><p>Move from bonds and energy to Lewis diagrams, resonance, and three-dimensional structure. Learn each topic, explore it interactively, then practice in the AP-style test environment.</p></header><section className="unit-practice-launch"><div><p className="eyebrow">WHOLE UNIT</p><h2>Ready to mix all seven topics?</h2><p>Choose interactive concept practice or a focused AP-style multiple-choice session.</p></div><div><button onClick={()=>navigate('/practice/concepts/2')}>Practice Concepts</button><button className="primary" onClick={()=>navigate('/practice/ap/2')}>Practice AP <span>→</span></button></div></section><div className="topic-list">{topics.map((t,i)=><article key={t.id}><span className="topic-num">{t.id}</span><div><p className="eyebrow">TOPIC {String(i+1).padStart(2,'0')}</p><h2>{t.title}</h2><p>{t.blurb}</p></div><div className="topic-actions"><button onClick={()=>navigate(`/learn/${t.id}`)}>Learn</button><button onClick={()=>navigate(`/practice/concepts/${t.id}`)}>Practice Concepts</button><button className="primary" onClick={()=>navigate(`/practice/ap/${t.id}`)}>Practice AP <span>→</span></button></div></article>)}</div></main>}
